In [2]:
import numpy as np

In [3]:
#create an empty array
arr1=np.array 
arr1

array([], dtype=float64)

In [5]:
my_list=[5,6,7,8,9,10]
print(my_list)
print(type(my_list))

[5, 6, 7, 8, 9, 10]
<class 'list'>


In [6]:
a=np.array(my_list)

In [7]:
a

array([ 5,  6,  7,  8,  9, 10])

In [11]:
type(a)

numpy.ndarray

In [12]:
a.ndim #number of dimensions in the array


1

In [13]:
a.size #size of an array is the no.of times


6

In [14]:
a.shape #shape of array

(6,)

Arrays can be of n dimensions

In [15]:
my_matrix=[[1,2,3,4],[5,6,7,8],[9,10,11,12]] #list of lists
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [16]:
b=np.array(my_matrix) #generates a 2d array
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
b.ndim

2

In [18]:
b.size

12

In [19]:
b.shape #rows - colums

(3, 4)

In [21]:
b.dtype #datatype of elements in array

dtype('int32')

In [23]:
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #3d array
arr1


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
arr1.ndim

3

In [26]:
arr1.size

12

In [27]:
arr1.shape

(2, 2, 3)

In [ ]:
22

Built-in Methods

In [28]:
arr2=arr1.reshape((1,3,4)) #reshape function takes the new shape array

In [29]:
arr2.shape

(1, 3, 4)

In [30]:
arr2


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

Arrange
#Return evenly spaced values within a given interval

In [32]:
#np.arange(start,end,step)
np.arange(15) #end ;default start at 0


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
np.arange(100,2,-4) #start ,end and step

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24,  20,  16,  12,   8,   4])

In [34]:
np.arange(0,11,2) #start end and step

array([ 0,  2,  4,  6,  8, 10])

Zeros and ones #generate arrays of zeros or ones

In [35]:
import numpy as np

In [36]:
np.zeros(3) #generates array in 1 dimension with all elaments 0

array([0., 0., 0.])

In [39]:
np.zeros((5,5)) #generates array in 2 dimension with all elements

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
np.ones(3)#generates array of 1 dimension where all elements in array


array([1., 1., 1.])

In [42]:
np.ones((4,5)) #generates array of dimensions where all elemements in array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
np.ones((4,5,3))


array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

Linespace #return evenly spaced numbers over a specified interval

In [45]:
import numpy as np

In [47]:
np.linspace(1,15) #default 50 observations 
#both the start and end are included in the array



array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [50]:
np.linspace(0,100,5) #equality spaced 5 values

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
#retstep ~ return step computed by linspace

In [54]:
np.linspace(0,100,5, retstep=True) #start #end (here end is included) and  default


(array([  0.,  25.,  50.,  75., 100.]), 25.0)

In [52]:
np.linspace(0,200,10) #default retstep=False

array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
        88.88888889, 111.11111111, 133.33333333, 155.55555556,
       177.77777778, 200.        ])

eye #Creates an identity matrix

In [55]:
np.eye(5) #generates 2d array of (5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#create an eye from a zeros array

Use of Copy function

In [104]:
import numpy as np
arr3=np.array([1,2,3,4,5,6,7,8,9])
arr4=np.array([10,11,12,13,14,15,16,17])

In [105]:
arr4=arr3
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
arr4[5]=30
arr4

array([ 1,  2,  3,  4,  5, 30,  7,  8,  9])

In [107]:
arr3

array([ 1,  2,  3,  4,  5, 30,  7,  8,  9])

In [108]:
arr5=arr3.copy()

In [110]:
arr5[1:]=100
arr5

array([  1, 100, 100, 100, 100, 100, 100, 100, 100])

Random (rand)

In [111]:
import numpy as np

In [112]:
np.random.rand()

0.533292529229543

In [113]:
np.random.rand(10) #rand gives value between 0 to 1


array([0.07228029, 0.21562954, 0.48576042, 0.78029038, 0.70183681,
       0.12174372, 0.20979632, 0.2513724 , 0.03351125, 0.70691211])

In [114]:
np.random.rand(10).reshape((2,5))

array([[0.78228075, 0.69870957, 0.67212233, 0.49735966, 0.23389236],
       [0.38488212, 0.99323506, 0.87815522, 0.37552929, 0.47961752]])

In [115]:
#creating array from unifrom distribution
new_arr=np.random.rand(5,3)

In [116]:
new_arr

array([[0.77352387, 0.36226981, 0.5270195 ],
       [0.57777716, 0.20553784, 0.52938085],
       [0.71694875, 0.28376108, 0.01756333],
       [0.21133915, 0.4107557 , 0.11814058],
       [0.07258231, 0.92708386, 0.7575446 ]])

randn #returnn a sample  (or samples) from the standard normal distribution

In [117]:
arr1

[1, 2, 3, 4, 5, 6]

In [118]:
arr1=np.random.randn(50)
arr1

array([-1.23902928,  1.25846545, -0.6964573 ,  0.15326862, -0.31433063,
       -1.70676816,  0.23362068, -2.24394927,  1.58912346,  0.16320117,
        0.80816919, -0.28714033, -0.23113483, -1.46956564, -0.6019678 ,
        0.02424288, -0.8008856 ,  0.559874  , -0.98854907, -0.00814189,
        0.17051796,  1.88509187,  0.1708401 ,  1.45771726,  0.2529017 ,
       -1.73503876, -0.20625827, -1.24849481,  0.21082711,  1.39051871,
       -0.18302456,  0.16344596,  1.80355907, -3.36026145, -1.99223716,
        0.27896071,  0.37123688,  0.45527738,  1.14332858,  1.25872245,
       -0.97806389,  0.4188723 , -1.0141172 ,  0.04711118, -0.89160792,
       -0.72186855, -0.2236039 ,  0.48000808, -0.34093217, -0.52048012])

randint



In [119]:
np.random.randint(1,100)

46

In [120]:
np.random.randint(1,100,10)

array([41, 20, 48, 37, 91, 50, 30, 38, 64, 87])

In [123]:
np.random.randint(40,60,50) #generating 50 values between 

array([53, 44, 45, 43, 51, 40, 42, 56, 48, 46, 44, 44, 45, 51, 46, 53, 43,
       49, 41, 52, 45, 59, 41, 48, 42, 40, 43, 58, 55, 54, 47, 42, 53, 45,
       42, 59, 51, 51, 41, 44, 44, 47, 48, 49, 52, 54, 41, 47, 42, 55])